### ISSUE TITLE
Initial Commit

### ISSUE THREAD

**Issue by sirthxalot** [sirthxalot/jekyll-starter#1]
## Situation

At this point we will have an empty project, ready to get feed with some data. Let's begin to tackle down the scaffold of the Jekyll Starter Template and lay down all the common parts we will need in order to start developing.

## Tasks

- [x] **Minor**: Add common project files.
- [x] **Feature**: Implement Gulp and Laravel Elixir for advanced assets workflow.
- [x] **Feature**: Implement basic structure and create common files.
- [x] **Feature**: Create the master layout related to the HTML5 Boilerplate project. 
- [x] **Feature**: Add basic assets in order to allow custom design.
