### ISSUE TITLE
Initial Commit

### ISSUE THREAD

**Issue by sirthxalot** [sirthxalot/jekyll-starter#1]
## Situation

At this point I will have an empty project ready to get feed with some data. So lets begin to scaffold the default structure and provide the common files of the project.

## Tasks

- [x] Add common project files.
- [x] Create skeleton of template related to the Jekyll and HTML5 Boilerplate project.
- [x] Define the dependencies and implement the default assets.
- [x] Implement the default layouts for the website.
- [x] Add basic pages, e.g: homepage, file not found (404) error page and a blog post.
