### ISSUE TITLE
Initial Commit

### ISSUE THREAD

**Issue by sirthxalot** [sirthxalot/jekyll-starter#1]
## Situation

At this point we will have an empty project ready to get feed with some data. Lets begin to tackle down the skeleton of the Jekyll Starter Template and provide the default assets, in order to get ready for development.

## Tasks

- [x] **Minor**: Add common project files.
- [x] **Feature**: Create skeleton of template related to the Jekyll and HTML5 Boilerplate project.
- [x] **Feature**: Define the dependencies and implement the default assets.
- [x] **Feature**: Implement the default layouts for the website.
- [x] **Feature**: Add basic pages, e.g: homepage and file not found (404) error page.
