### ISSUE TITLE
Scaffold Page Layout

### ISSUE THREAD

**Issue by sirthxalot** [sirthxalot/jekyll-starter#2]
## Situation

We will need some point from where we can start develop our page layout segments, e.g: header, content and footer. So lets begin to implement the default structure of page layout and setup everything to start.

## Tasks

- [x] **Minor**: Add default classes to html attribute of pages and post layout.
- [x] **Feature**: Implement header and footer segment into page layout.
- [x] **Feature**: Setup page for header, content and footer layout.
