### ISSUE TITLE
Implement Third Party Modules

### ISSUE THREAD

**Issue by sirthxalot** [sirthxalot/jekyll-starter#2]
## Situation

We will need some Third Party Modules which will help to design the pages. Luckly most of our dependencies can be found at NPM where we are going to require them. In this step I am going to install the dependencies and manage them using Gulp and Laravel Elixir, but they will not implemented at this stage, some of them will be optional anyway.

## Tasks

- [x] **Feature**: Require default packages in order to provide the assets.
- [x] **Feature**: Add public web fonts which can be used within the pages design.

## Dependencies

- [x] Implement [Anchor.js](http://bryanbraun.github.io/anchorjs/) plugin dependency.
- [x] Implement [Chart.js](http://www.chartjs.org/) plugin dependency.
- [x] Implement [Clipboard.js](https://clipboardjs.com/) plugin dependency.
- [x] Implement Firebase plugin dependency.
- [x] Implement FontAwesome default dependency.
- [x] Implement JavaScript Cookie default dependency.
- [x] Implement jQuery default dependency.
- [x] Implement MD5 JavaScript default dependency.
- [x] Implement [Moment.js](http://momentjs.com/) default dependency.
- [x] Implement Retina.js default dependency.
- [x] Implement Simple Jekyll Search default dependency.
- [x] Implement SnapSVG plugin dependeny.
- [x] Implement [Tether.js](http://tether.io/) default dependency.
- [x] Implement Twitter Bootstrap 4 default dependency.
- [x] Implement Typed.js plugin dependency.
- [x] Implement Vue.js default dependency.
