### ISSUE TITLE
JavaScript Revision 001

### ISSUE THREAD

**Issue by sirthxalot** [sirthxalot/jekyll-starter#2]
## Tasks

- [x] Add Webpack Support for Laravel Elixir
- [x] Require lodash JavaScript Library
- [ ] Revise `gulpfile.js` using Webpack
- [ ] Allow to use CDN links when using `page.js`
- [ ] Remove Fullpage dependency
- [ ] Seperate Page and Blog JavaScript
