### ISSUE TITLE
Header Segment

### ISSUE THREAD

**Issue by sirthxalot** [sirthxalot/jekyll-starter#3]
## Situation

Lets begin to design the header also known as the top bar, which will be used in order to give the client a quick navigation entry point.

## Tasks

- [x] **Feature**: Design the header segment.
- [x] **Feature**: Implement brand component within the header segment
- [x] **Minor**: Implement header bar segment
- [x] **Feature**: Implement menu component within the header segment
- [x] **Feature**: Implement search component within the header segment
