### ISSUE TITLE
Footer Segment

### ISSUE THREAD

**Issue by sirthxalot** [sirthxalot/jekyll-starter#4]
# Situation

Yet our footer already sticks at the bottom which is simply beautiful. But it looks a little bit funky so we have to design it and starting to add the footer segments: Copyright, Navigation and Social.

## Tasks

- [x] **Feature**: Implement the footer segments consist of a copyright and a hub component.
- [x] **Feature**: Implement and design the footer copyright component.
- [x] **Feature**: Implement and design the footer hub component.
- [x] **Feature**: Implement the page-row layout and set it as default page layout.
- [x] **Minor**: Add an empty imprint page in order to use within footer hub navigation.
