### ISSUE TITLE
Revise Page Layout Implementation

### ISSUE THREAD

**Issue by sirthxalot** [sirthxalot/jekyll-starter#5]
## Situation

The default page layout segments and components has been integrated. Now we have to revise the stylesheets and restructure a bit. After doing this and what I have seen so far it will be may more than a bit, I am going to test everything out.

## Tasks

- [x] **Feature**: Use data in order to generate the footer navigation similar to the header segment.
- [x] **Minor**: Move common styles into componenets since they represent the same.
- [x] **Minor**: Checkout all HTML partials and layouts for semantic errors and if the stick to the coding guide.
- [x] **Minor**: Check for BEM conventition and if we have classed everything correctly.
- [x] **Minor**: Checkout for unecessary or falsy styles.
